name: Nightly Releases

on:
  push:
    branches: [ dev, ci/** ]
  workflow_dispatch:

jobs:
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: flucoma/actions/env@v5        
  #     - uses: flucoma/actions/docs@v5
  #       with:
  #         target: MAKE_CLI_REF
  # 
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: docs
  #         path: build/cli_ref

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: flucoma/actions/env@v5      
    - uses: flucoma/actions/cli@v5
      with:
        branch: origin/dev
    - name: compress archive
      run: zip -r FluCoMa-CLI-Windows-nightly.zip FluidCorpusManipulation
      working-directory: release-packaging

    - uses: actions/upload-artifact@v2
      with:
        name: winbuild
        path: release-packaging/FluCoMa-CLI-Windows-nightly.zip
    
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v5      
      - uses: flucoma/actions/cli@v5
        with:
          branch: origin/dev
      - name: compress archive
        run: zip -r FluCoMa-CLI-Mac-nightly.zip FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: macbuild
          path: release-packaging/FluCoMa-CLI-Mac-nightly.zip
      
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v5
      - uses: flucoma/actions/cli@v5
        with:
          branch: origin/dev
      - name: compress archive
        run: tar -zcvf FluCoMa-CLI-Linux-nightly.tar.gz FluidCorpusManipulation
        working-directory: release-packaging 
      - uses: actions/upload-artifact@v2
        with:
          name: linuxbuild
          path: release-packaging/FluCoMa-CLI-Linux-nightly.tar.gz
      
  release:
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: docs
      #     path: docs
      # 
      - uses: actions/download-artifact@v2
        with:
          name: linuxbuild
          # path: linux

      - uses: actions/download-artifact@v2
        with:
          name: macbuild
          # path: mac

      - uses: actions/download-artifact@v2
        with:
          name: winbuild
          # path: win

      #### LINUX ####
      # - name: untar
      #   run: tar zxvf linuxbuild.tar.gz -C .
      #   working-directory: ./linux
      # 
      # - name: copy docs to linux
      #   run: cp -r docs linux/release-packaging/FluidCorpusManipulation
      # 
      # - name: compress linux
      #   run: zip -r ../../FluCoMa-CLI-Linux-nightly.zip .
      #   working-directory: linux/release-packaging

      #### MAC ####
      # - name: see
      #   run : ls -R
      # 
      # - name: untar
      #   run: tar zxvf macbuild.tar.gz -C .
      #   working-directory: ./mac
      # 
      # - name: copy docs to mac
      #   run: cp -r docs mac/release-packaging/FluidCorpusManipulation
      # 
      # - name: compress mac
      #   run: zip -r ../../FluCoMa-CLI-Mac-nightly.zip .
      #   working-directory: mac/release-packaging

      #### WINDOWS ####
      # - name: untar
      #   run: tar zxvf winbuild.tar.gz -C .
      #   working-directory: ./win
      # 
      # - name: copy docs to win
      #   run: cp -r docs win/release-packaging/FluidCorpusManipulation
      # 
      # - name: compress mac
      #   run: zip -r ../../FluCoMa-CLI-Windows-nightly.zip .
      #   working-directory: win/release-packaging
      # 
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: nightly # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: FluCoMa CLI Nightly Release
          body: "This is a nightly build of the FluCoMa CLI tools. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
          files: FluCoMa-CLI-*
          prerelease: true
          tag_name: nightly
          draft: false


        
