name: Release
on:
  workflow_dispatch:
    inputs:
      baseBranch:
        description: 'Base branch to deploy core from'
        required: false
        default: 'main'
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.baseBranch }}
      - uses: flucoma/actions/docs@v4
        with:
          target: MAKE_CLI_REF
          branch: ${{ github.event.inputs.baseBranch }}

      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: build/cli_ref
          
  linux:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.baseBranch }}
      - uses: flucoma/actions/cli@v4    
      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: linux                                                                                                                                                                
          path: release-packaging

      - id: get-version
        run: echo "::set-output name=version::$(cat flucoma.version.rc)"
        working-directory: core

  mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.baseBranch }} 
      - uses: flucoma/actions/cli@v4

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: mac                                                                                                                                                                 
          path: release-packaging

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.baseBranch }}        
      - uses: flucoma/actions/cli@v4

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: windows                                                                                                                                                                
          path: "release-packaging"
  
  release:
    runs-on: ubuntu-latest
    needs: [mac, windows, linux, docs]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      #### LINUX ####
      - uses: actions/download-artifact@v2
        with:
          name: linux
          path: linux

      - name: copy docs to linux
        run: cp -r docs linux/FluidCorpusManipulation

      - name: compress linux
        run: zip -r ../FluCoMa-CLI-Linux-"${{ needs.linux.outputs.version }}"zip .
        working-directory: linux

      #### MAC ####
      - uses: actions/download-artifact@v2
        with:
          name: mac
          path: mac

      - name: copy docs to mac
        run: cp -r docs mac/FluidCorpusManipulation

      - name: compress mac
        run: zip -r ../FluCoMa-PD-Mac-"${{ needs.linux.outputs.version }}".zip .
        working-directory: mac

      # #### WINDOWS ####
      - uses: actions/download-artifact@v2
        with:
          name: windows
          path: win

      - name: copy docs to windows
        run: cp -r docs win/FluidCorpusManipulation

      - name: compress windows
        run: zip -r ../FluCoMa-PD-Windows-"${{ needs.linux.outputs.version }}".zip .
        working-directory: win
      
      #### UPLOAD RELEASE ####
      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.linux.outputs.version }}
          body: "This is a release build of the FluCoMa CLI tools. The build hash is ${{ github.sha }}"
          files: FluCoMa*.zip
          prerelease: false
          tag_name: ${{ needs.linux.outputs.version }}
          draft: false
