name: Release
on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to deploy core from'
        required: false
        default: 'main'
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.base_branch }}
      - uses: flucoma/actions/docs@v4
        with:
          target: MAKE_CLI_REF
          branch: ${{ github.event.inputs.base_branch }}

      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: build/cli_ref

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.base_branch }}        
      - uses: flucoma/actions/cli@v4

      - name: compress archive
        run: tar -zcvf winbuild.tar.gz release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: winbuild
          path: winbuild.tar.gz

  mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.base_branch }} 
      - uses: flucoma/actions/cli@v4

      - name: compress archive
        run: tar -zcvf macbuild.tar.gz release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: macbuild
          path: macbuild.tar.gz
  
          
  linux:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v4
        with:
          branch: ${{ github.event.inputs.base_branch }}
      - uses: flucoma/actions/cli@v4    

      - name: compress archive
        run: tar -zcvf linuxbuild.tar.gz release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: linuxbuild
          path: linuxbuild.tar.gz

      - id: get-version
        run: echo "::set-output name=version::$(cat flucoma.version.rc)"
        working-directory: core

  release:
    runs-on: ubuntu-latest
    needs: [mac, windows, linux, docs]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      
      - uses: actions/download-artifact@v2
        with:
          name: linuxbuild
          path: linux

      - uses: actions/download-artifact@v2
        with:
          name: macbuild
          path: mac

      - uses: actions/download-artifact@v2
        with:
          name: winbuild
          path: win

      #### LINUX ####
      - name: untar
        run: tar zxvf linuxbuild.tar.gz -C .
        working-directory: ./linux

      - name: copy docs to linux
        run: cp -r docs linux/release-packaging/FluidCorpusManipulation

      - name: compress linux
        run: zip -r ../../FluCoMa-CLI-Linux.zip .
        working-directory: linux/release-packaging

      #### MAC ####
      - name: untar
        run: tar zxvf macbuild.tar.gz -C .
        working-directory: ./mac

      - name: copy docs to mac
        run: cp -r docs mac/release-packaging/FluidCorpusManipulation

      - name: compress mac
        run: zip -r ../../FluCoMa-CLI-Mac.zip .
        working-directory: mac/release-packaging

      #### WINDOWS ####
      - name: untar
        run: tar zxvf winbuild.tar.gz -C .
        working-directory: ./win

      - name: copy docs to win
        run: cp -r docs win/release-packaging/FluidCorpusManipulation

      - name: compress mac
        run: zip -r ../../FluCoMa-CLI-Windows.zip .
        working-directory: win/release-packaging
      
      #### UPLOAD RELEASE ####
      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.linux.outputs.version }}
          body: "This is a release build of the FluCoMa CLI tools. The build hash is ${{ github.sha }}"
          files: FluCoMa*.zip
          prerelease: true
          tag_name: ${{ needs.linux.outputs.version }}
          draft: false
