name: signing

on:
  workflow_dispatch:
  push:
    branches: [ dev, ci/** ]

jobs:
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: flucoma/actions/env@v5      
      - uses: flucoma/actions/cli@v5
        with:
          branch: origin/dev
    
      - name: sign binaries
        uses: flucoma/actions/distribution@main
        with:
          glob: 'fluid -t x'
          package: 'release-packaging'
          codesign_options: 'runtime'
          output_type: 'dmg'
          output: FluCoMa-CLI-Mac
          cert: ${{ secrets.CERT }}
          certpwd: ${{ secrets.CERTPWD }}
          teamid: ${{ secrets.WWDRTEAMID }}
          apppwd: ${{ secrets.APPSTORECONNECTPWD }}
          appusr: ${{ secrets.APPSTORECONNECTUSERNAME }}

      - uses: actions/upload-artifact@v2
        with:
          name: macbuild
          path: release-packaging/FluCoMa-CLI-Mac.dmg

  release:
    runs-on: ubuntu-latest
    needs: [macos]
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: macbuild

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: signing-test # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: FluCoMa CLI Nightly Release
          body: "This is a nightly build of the FluCoMa CLI tools. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
          files: FluCoMa*
          prerelease: true
          tag_name: signing-test
          draft: false


        
